from cncs import displayFluxResPlots, calcFluxRes
import matplotlib.pyplot as plt

calcFluxRes("HF", 10.)
calcFluxRes("HR", 10.)
calcFluxRes("HF", 80.)


calcFluxRes("HF", 30.)
calcFluxRes("HF", 12.)
calcFluxRes("HF", 5.)
calcFluxRes("HF", 3.32)
calcFluxRes("HF", 3)
calcFluxRes("HF", 1.55)
calcFluxRes("HF", 1.0)

print('***')

calcFluxRes("HF", 12)
calcFluxRes("HF", 3.32)
calcFluxRes("HF", 1.55)
calcFluxRes("HF", 1.00)
calcFluxRes("HF", 15.00)
calcFluxRes("HF", 12.00)
calcFluxRes("AI", 12.00)
calcFluxRes("HR", 12.00)
calcFluxRes("HF", 5.00)
calcFluxRes("HF", 6.00)
calcFluxRes("HF", 7.00)
calcFluxRes("HF", 80)
calcFluxRes("HF", 50)
calcFluxRes("HF", 40)
calcFluxRes("HF", 37.5)
calcFluxRes("HF", 30)
calcFluxRes("HF", 12)
calcFluxRes("HF", 2.0)
calcFluxRes("HF", 1.0)
calcFluxRes("HF", 20.0)
calcFluxRes("AI", 3.32)
calcFluxRes("HF", 3.32)
calcFluxRes("HF", 1.5)
calcFluxRes("HF", 16)
calcFluxRes("HF", 3.32)
calcFluxRes("HF", 1.5)
calcFluxRes("HF", 1.)
calcFluxRes("HF", .54)


displayFluxResPlots()
plt.close('all')
